serviceAccount:
  create: true
  name: fluent-bit

backend:
  type: es  # Elasticsearch/OpenSearch type

output:
  es:
    enabled: true
    host: log-proxy.example.com
    port: 443
    tls: true
    http_user: "your_user"      # optional, if basic auth used
    http_passwd: "your_pass"    # optional, if basic auth used
    index: kubernetes-logs
    type: _doc
    logstash_prefix: fluentbit
    replace_dots: true

input:
  tail:
    enabled: true
    path: /var/log/containers/*.log
    parser: docker
    tag: kube.*
    refresh_interval: 5
    mem_buf_limit: 5MB
    skip_long_lines: true

filters:
  kubernetes:
    enabled: true
    match: kube.*
    buffer_size: 0
    kube_url: https://kubernetes.default.svc:443
    merge_log: true
    k8s_logging_parser: true
