# Fluent Bit Helm Chart values override
serviceAccount:
  create: true
  name: fluent-bit

rbac:
  create: true

backend:
  type: es
  es:
    host: "your-opensearch-host"       # e.g., search-cluster.us-east-1.es.amazonaws.com
    port: 443
    index: "fluentbit"
    type: "_doc"
    logstashPrefix: "fluentbit"
    tls: true
    httpUser: "${OPENSEARCH_USER}"         # From secret
    httpPassword: "${OPENSEARCH_PASSWORD}" # From secret
    tlsVerify: false

envFrom:
  - secretRef:
      name: fluentbit-opensearch-secret

input:
  tail:
    enabled: true
    path: "/var/log/containers/*.log"
    parser: docker
    tag: kube.*
    refreshInterval: 5
    memBufLimit: 5MB
    skipLongLines: true

filters:
  kubernetes:
    enabled: true
    match: kube.*
    mergeLog: true
    keepLog: false
    k8sTagPrefix: "kube.var.log.containers."
    annotations: false
